In [ ]:
#5. Consider the Given “Iris” data set and  classify iris flowers among three species (setosa, versicolor, or virginica) from measurements of sepals and petals' length and width.

In [1]:
 import numpy as np, pandas as pd, matplotlib.pyplot as plt 
from sklearn import tree, metrics, model_selection, preprocessing

In [3]:
# load the iris data
df = pd.read_csv('/iris.csv')
df.head(5)

sepal.length  sepal.width  petal.length  petal.width species
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [4]:
df['species_label'],i = pd.factorize(df['species'])
df['species'].unique()
df['species_label'].unique()

array([0, 1, 2])

In [5]:
# select features
y = df['species_label'] #Dependent feature
X = df[['sepal.length', 'sepal.width']] #Independent features (subset)

In [6]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species_label, Length: 150, dtype: int64

In [7]:
X

sepal.length  sepal.width
0             5.1          3.5
1             4.9          3.0
2             4.7          3.2
3             4.6          3.1
4             5.0          3.6
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[150 rows x 2 columns]

In [8]:
# split data randomly into 70% training and 30% test
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.3, random_state=0)

In [9]:
# train the decision tree
dtree = tree.DecisionTreeClassifier(criterion='entropy', max_depth=3)
dtree.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=3, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [11]:
# testing the model
y_pred = dtree.predict(X_test)
y_pred

array([1, 2, 0, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 1, 0, 0, 1, 1,
       0, 0, 2, 0, 0, 2, 1, 0, 2, 0, 0, 2, 2, 1, 0, 2, 2, 1, 2, 0, 2, 0,
       0])

In [12]:
# acuuracy
accuracy = metrics.accuracy_score(y_test, y_pred)
print('Accuracy: {:.2f}'.format(accuracy))

Accuracy: 0.67


In [13]:
from sklearn.metrics import  confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[16  0  0]
 [ 1  5 12]
 [ 0  2  9]]


In [ ]:
# Assignment
1.	Increase the accuracy of the model
2.	Use the different criterion method
3.	Print the precision, recall and f1-scores for the model